//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Template.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class FileLocationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FileLocationSettings defaultInstance = ((FileLocationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FileLocationSettings())));
        
        public static FileLocationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Hex2000_Location {
            get {
                return ((string)(this["Hex2000_Location"]));
            }
            set {
                this["Hex2000_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Coff_Location {
            get {
                return ((string)(this["Coff_Location"]));
            }
            set {
                this["Coff_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string A00_Destination {
            get {
                return ((string)(this["A00_Destination"]));
            }
            set {
                this["A00_Destination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string A00_Location {
            get {
                return ((string)(this["A00_Location"]));
            }
            set {
                this["A00_Location"] = value;
            }
        }
    }
}
